### ISSUE TITLE
Define Error Code of WebTransport over QUIC

### ISSUE THREAD

**Issue by flano-yuki** [vasilvv/webtransport#15]
In WebTransport over QUIC, when an invalid  Client Indication is received, the server	 treats the connection as an error([section 6](https://vasilvv.github.io/webtransport/draft-vvv-webtransport-quic.html#rfc.section.6)).

This is an error that occurred in a layer above the QUIC, so I think the connection should be closed with CONNECTION_CLOSE (0x1d) indicating an error in the application using the QUIC.

I think it is valuable to define an error code for WebTransport over QUIC.
( [draft-ietf-quic-transport-24 section 20.1](https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-20.1) saids "the management of application error codes is left to application protocols." )

and, by specifying the error code that the endpoint uses when it close the connection, the specification becomes clear.

for example
```
- WQ_NO_ERROR 
- WQ_INVALID_CLIENT_INDICATION
- WQ_NOT_AUTHORITATIVE_ORGIN
- WQ_OTHER_ERROR
...
```

**Comment by flano-yuki** [comment]
I realized that Error Code is related to the [WICG/web-transport](https://github.com/WICG/web-transport).

I createted https://github.com/WICG/web-transport/issues/80 .
Please point it out if there are any mistakes in my opinion.

**Comment by kixelated** [comment]
I agree, CONNECTION_CLOSE should provide an error code indicating why the connection was refused.

**Comment by LPardue** [comment]
I seem to remember seeing non-zero error codes from other endpoints when interoperating. If so, I have no clue what those codes were supposed to mean. I think it would be useful to have some defined in the next draft version.

**Comment by vasilvv** [comment]
I think the non-zero error codes probably were random HTTP/3 error codes, because those are the only codes that Google's QUIC library supports (that's a known bug).

I see three options for reporting handshake error:
1) An application CONNECTION_CLOSE,
2) A RESET_STREAM on the handshake stream,
3) An error status code on the handshake stream.

If we go with 1, we would have to reserve some of the application error code space.  If we go with 2 or 3, we would have to describe how the server has to keep the connection open for some time in order to allow for retransmission of the RESET_STREAM/response error header.

**Comment by DavidSchinazi** [comment]
Closing this issue because the QuicTransport draft has been removed from this repository.
